### ISSUE TITLE
Error: distutils.errors.DistutilsPlatformError: Unable to find vcvarsall.bat

### ISSUE THREAD

**Issue by EkremDincel** [manicmaniac/inline#1]
When I am trying that example:
````py
import inline
c = inline.c(r'''
int add(int a, int b) {
    return a + b;
}
''')
````
I am getting this error:
````py
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    inline.c(r'''
  File "C:\Users\Dinçel\AppData\Local\Programs\Python\Python38\lib\site-packages\inline.py", line 29, in c
    path = _cc_build_shared_lib(source, '.c', libraries)
  File "C:\Users\Dinçel\AppData\Local\Programs\Python\Python38\lib\site-packages\inline.py", line 64, in _cc_build_shared_lib
    objs = cc.compile((f.name,), tempdir, extra_postargs=args)
  File "C:\Users\Dinçel\AppData\Local\Programs\Python\Python38\lib\distutils\_msvccompiler.py", line 360, in compile
    self.initialize()
  File "C:\Users\Dinçel\AppData\Local\Programs\Python\Python38\lib\distutils\_msvccompiler.py", line 253, in initialize
    vc_env = _get_vc_env(plat_spec)
  File "C:\Users\Dinçel\AppData\Local\Programs\Python\Python38\lib\distutils\_msvccompiler.py", line 147, in _get_vc_env
    raise DistutilsPlatformError("Unable to find vcvarsall.bat")
distutils.errors.DistutilsPlatformError: Unable to find vcvarsall.bat
````
What should I do?

Windows 10
Python3.8.0

**Comment by manicmaniac** [comment]
I don't know much about Windows but I guess `vcvarsall.bat` (and other C compiler toolchains) would be included in VisualStudio.
Have you already installed VisualStudio? If so, please tell me the version.

**Comment by EkremDincel** [comment]
No, I have not VisualStudio. And probably I can't install it. My computer is old. Can I use any other compiler or is there any way to only donwload compiler of VisualStudio?

**Comment by manicmaniac** [comment]
Hmm... I don't have a good idea.

I've never tested that but how about installing [gcc](http://www.mingw.org/) instead?
Maybe you need to specify gcc as a default compiler in `distutils.cfg`.

See https://cython.readthedocs.io/en/latest/src/tutorial/appendix.html for more information.
